-- MIT License
--
-- Copyright (c) 2025 Andrew Vasilyev <me@retran.me>
--
-- Permission is hereby granted, free of charge, to any person obtaining a copy
-- of this software and associated documentation files (the "Software"), to deal
-- in the Software without restriction, including without limitation the rights
-- to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
-- copies of the Software, and to permit persons to whom the Software is
-- furnished to do so, subject to the following conditions:
--
-- The above copyright notice and this permission notice shall be included in
-- all copies or substantial portions of the Software.
--
-- THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
-- IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
-- FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
-- AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
-- LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
-- OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
-- THE SOFTWARE.
--
-- @file: lua/meow/review/config/meta.lua
-- @brief: LuaLS type annotations for meow.review.nvim configuration
-- @author: Andrew Vasilyev
-- @license: MIT

---@class meow.review.Annotation
---@field id string Unique annotation ID ("timestamp_random").
---@field file string Relative file path from the project root.
---@field lnum number 1-based start line number.
---@field end_lnum number 1-based end line number.
---@field type string Annotation type key (e.g. "ISSUE", "SUGGESTION", "NOTE", or custom).
---@field text string Review comment text.
---@field context string|nil Treesitter symbol name at annotation time, or nil.
---@field snippet string|nil Source lines captured around the range (with line numbers), or nil.
---@field snippet_start number|nil First line number in the snippet (1-based), or nil.
---@field hunk_head string|nil Unified-diff hunk header (e.g. "@@ -1,4 +1,4 @@"), or nil.
---@field hunk_start number|nil Hunk start line in the new file, or nil.
---@field hunk_end number|nil Hunk end line in the new file, or nil.
---@field timestamp number Unix timestamp when the annotation was created.

---@alias meow.review.ExporterFn fun(markdown: string, root: string)

---@class meow.review.AnnotationType
---@field icon? string Sign column icon character (default varies by built-in type).
---@field hl? string Highlight group name (default varies by built-in type).
---@field label? string Display label used in the modal and export (defaults to the key name).
---@field sign_name? string Neovim sign name; auto-derived as "MeowReview"..key if omitted.

---@class meow.review.Config
---@field context_lines? number Lines of source context to capture before and after the annotated range (default 3). Set to 0 to disable snippet capture.
---@field disabled_exporters? string[] Built-in exporter names to disable (e.g. {"clipboard"} to disable the clipboard exporter).
---@field default_exporter? string Exporter to run when no name is given to `:MeowReview export` (default "clipboard").
---@field default_formatter? string Formatter to use when no formatter is specified (default "markdown"). Built-ins: "markdown", "json".
---@field export_filename? string Filename written by the `file` and `file_prompt` exporters (default ".cache/meow-review/review.md"). Relative paths are resolved against the project root.
---@field store_path? string Path to the annotation store JSON file. Relative paths are resolved against the project root; absolute paths are used as-is. Parent directories are created automatically. Default: ".cache/meow-review/annotations.json".
---@field modal_width? number Width (in columns) of the add/edit comment modal. Default: 64.
---@field modal_height? number Height (in lines) of the add/edit comment modal. Default: 6.
---@field modal_cycle_key? string Insert-mode key used to cycle the annotation type in the add/edit modal. Default: "<C-t>". Change if it conflicts with your mappings.
---@field auto_gitignore? string|boolean Whether to add the store file path to .gitignore. "always" adds it silently, "prompt" (default) shows a vim.ui.select prompt once, false disables.
---@field annotation_types? table<string, meow.review.AnnotationType> Custom annotation type definitions. Replaces the default set (ISSUE, SUGGESTION, NOTE) when provided.
---@field annotation_type_order? string[] Tab-cycling order for the add-modal. Defaults to sorted keys of annotation_types.
---@field prompt_preamble? string Text inserted after the document heading in the exported Markdown. Defaults to an instruction that asks the AI agent to apply each annotation as a targeted fix. Set to "" to omit it.

---@type meow.review.Config | fun(): meow.review.Config | nil
vim.g.meow_review = vim.g.meow_review
